name: Run Jest Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # ou la version de Node.js que tu utilises

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: npx jest --coverage
